CREATE TABLE Item (
    ItemId INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    "Description" NVARCHAR(250) NOT NULL,
    IsComplete BIT NOT NULL DEFAULT 0,
    CreationDate DATETIME NOT NULL DEFAULT SYSUTCDATETIME()
);
GO